### ISSUE TITLE
Fatal Error gotten after installing paystack 1.0.0.6.tgz 

### ISSUE THREAD

**Issue by ChidinmaKO** [PaystackHQ/paystack-magento#3]
Tried integrating Paystack for magento... installed 1.0.0.6.tgz and I kept getting errors..
I got this when I returned to admin and clicked on Payment methods.
"Fatal error: Class 'Paystack_Inline_Helper_Data' not found in /home/content/93/13959193/html/app/Mage.php on line 547"

The site is running on Magento 1.9.2.4

**Comment by ibrahimlawal** [comment]
Hey @ChidinmaKO Thanks for reporting this. Kindly check here **Admin Panel -> System -> Tools -> Compilation** to see if you have enabled compilation on Magento.  Click on the Disable button, then try again

**Comment by ChidinmaKO** [comment]
Thank you @ibrahimlawal I did that... It returned a "Parse error: syntax error, unexpected '[' in /home/content/93/13959193/html/app/code/community/Paystack/Inline/Helper/Data.php on line 48" instead.

**Comment by ibrahimlawal** [comment]
Glad that helped @chidinmaKO . Please confirm that your php version is at least 5.4 . The plugin requires at least that or higher

**Comment by ChidinmaKO** [comment]
Yes @ibrahimlawal my php version is 5.4.

**Comment by ibrahimlawal** [comment]
@ChidinmaKO Weird then. Is this online? I can take a look for you

**Comment by hellodemola** [comment]
Please, how was this resolved because I am also getting the same error Parse error: syntax error, unexpected '[' in /home/content/25/14069525/html/app/code/community/Paystack/Inline/Helper/Data.php on line 49

**Comment by hellodemola** [comment]
Ok. The problem was on line 49. 
Solution: We concatenated ['.'] the stray with the array. That solved it for me.
` $charid .= **'0123456789abcdef'.array(rand(0, $max));**`
