### ISSUE TITLE
Redirect to Success Page not work on Magento 1.9.2.4

### ISSUE THREAD

**Issue by alan-qbasic** [PaystackHQ/paystack-magento#6]
Am using the Paystack Inline Module 1.0.0.6 for my Magento which i installed via the Magento Connect but i am having problem redirecting to a success page after a successful transaction.

Am using 
Magento 1.9.2.4
PHP Version 5.6.30
Paystack_Inline | 1.0.0.6 (stable)

**Comment by ibrahimlawal** [comment]
Any technical information of the error? @alan-qbasic

**Comment by alan-qbasic** [comment]
I guess none because i did the installation as requested. This is the screen it always redirect to after the transaction

![image](https://user-images.githubusercontent.com/29778801/32780283-fdc899e8-c940-11e7-986b-9dc314623704.png)

**Comment by ibrahimlawal** [comment]
Please open your error logs and Magento admin error messages to check

**Comment by alan-qbasic** [comment]
I got this from one of my logs

/magento1/index.php/admin/system_config/edit/section/payment/key/16abfb31df44681d96c5ca39104b33bf/ HTTP/1.1" 200 447569
::1 - - [14/Nov/2017:13:48:51 +0100] "POST /magento1/index.php/admin/system_config/save/section/payment/key/6c5f03e9069529f786482d09d25302a7/ HTTP/1.1" 302 -
::1 - - [14/Nov/2017:13:48:56 +0100] "POST /magento1/app/etc/local.xml HTTP/1.1" 403 235
::1 - - [14/Nov/2017:13:48:53 +0100] "GET /magento1/index.php/admin/system_config/edit/section/payment/key/16abfb31df44681d96c5ca39104b33bf/ HTTP/1.1" 200 447688
::1 - - [14/Nov/2017:13:49:04 +0100] "GET /magento1/paystack/payment/pop/ HTTP/1.1" 200 60221
::1 - - [14/Nov/2017:13:50:42 +0100] "GET /magento1/paystack/payment/response/?orderId=100000036&reference=100000036-2207-4acc-b258-71f279b1f264 HTTP/1.1" 302 -
::1 - - [14/Nov/2017:13:50:43 +0100] "GET /magento1/checkout/cart/ HTTP/1.1" 200 51118

**Comment by ibrahimlawal** [comment]
Any error on Magento Admin?

**Comment by alan-qbasic** [comment]
None

**Comment by steveamaza** [comment]
Hey @alan-qbasic,
Is there a link we can test this out to see?
Can you elaborate on the steps you took to install the plugin?

**Comment by alan-qbasic** [comment]
You can check it here http://104.197.114.217/havilah/

1. I downloaded Paystack_Inline-1.0.0.6.tgz
2. I installed the plugin via Magento Connecto Manager and it was successful
3. I did my configuration with the Test public and secret key provided then i test run it

**Comment by ibrahimlawal** [comment]
weird, without the actual error message, it's hard understanding what went wrong. Does your server have any error logs?

**Comment by alan-qbasic** [comment]
Hey @ibrahimlawal 
I was going through the PaymentController.php in the plugin and i realize the page was redirecting to

Mage_Core_Controller_Varien_Action::_redirect('checkout/cart');

I then commented it out and redirect it to

Mage_Core_Controller_Varien_Action::_redirect('checkout/onepage/success');

Why is it executing if(!$success) even after the interface shows successful payment.

![image](https://user-images.githubusercontent.com/29778801/32945636-7a321234-cb94-11e7-8f9f-2317da4ef446.png)

**Comment by ibrahimlawal** [comment]
Awesome getting this far. Love that you can edit the code. Please try dumping the raw response from Paystack after we call the verify. That will tell us something about the error

**Comment by alan-qbasic** [comment]
ok boss

**Comment by alan-qbasic** [comment]
object(stdClass)#17 (1) { ["error"]=> string(73) "cURL said:SSL certificate problem: unable to get local issuer certificate" } 

I think it has to do with the SSL

**Comment by ibrahimlawal** [comment]
This may be of help: https://github.com/yabacon/paystack-php/wiki/cURL-error-60:-SSL-certificate-problem:-unable-to-get-local-issuer-certificate-(see-http:--curl.haxx.se-libcurl-c-libcurl-errors.html)

**Comment by alan-qbasic** [comment]
Thank you Boss!!

**Comment by alan-qbasic** [comment]
It's working now. 
Thank you so much @ibrahimlawal and @steveamaza .

**Comment by ibrahimlawal** [comment]
Awesome! Glad that's sorted. Thank you for choosing Paystack.
