### ISSUE TITLE
Website crashing after installing paystack

### ISSUE THREAD

**Issue by dolispy** [PaystackHQ/paystack-magento#9]
# Problem/Motivation
I tried to install the paystack plugin on my site and it keeps crashing. I tried using the magento connect and tried uploading the plugin manually through FileZilla. 
## Proposed resolution
(Description of the proposed solution, the rationale behind it, and workarounds for people who cannot use the patch.)
I have a theme which carries its own package.xml file. Is there a way I can go around this or add to the previous package.xml file because I think the issue could be from there.

## Repeatable
Always|Sometimes|Specific conditions|Specific times

(If it is a bug, you are reporting lease specify:)

## Steps to repeat: (Describe how the issue can be repeated by someone who is to work on it)
1. Step 1
2. Step 2
3. ...

## Expected Results:
(What you expected steps 1, 2 and 3 to give)

## Actual Results:
(What is gave including any error messages, memory dump etc that can help)

**Comment by steveamaza** [comment]
Hi @dolispy, follow the installation steps on the README file (the direct upload method) and let me know how it goes

**Comment by dolispy** [comment]
Hi @steveamaza , i followed the steps and i got this error when clearing the cache
Package installed: 
 community Paystack_Inline 1.0.0.7

Cleaning cache
....
Exception during cache and session cleaning

**Comment by steveamaza** [comment]
Hello @ibrahimlawal, I missed this response. Any idea what could be happening here? @dolispy, sincere apologies. Were you able to resolve?

**Comment by Dscnlag** [comment]
When is the release for Magento 2 version.
I need to install on m2 server

**Comment by steveamaza** [comment]
@Dscnlag please see https://paystack.helpscoutdocs.com/article/88-how-to-setup-paystack-on-magento-2
